# Generated by Django 4.0.3 on 2022-05-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_alter_post_reciever'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, default='cover.png', upload_to='covers'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
