# Generated by Django 4.0.3 on 2022-05-05 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_alter_category_cover_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publication.category'),
        ),
    ]
