# Generated by Django 4.0.3 on 2022-05-05 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0009_alter_post_reciever_alter_post_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reciever',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='publication.category'),
        ),
    ]
